<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>
      $(DotNetVersion);
      $(DotNetVersion)-windows10.0.26100
    </TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Target Name="UnoDumpTargetFrameworks" />
</Project>
