<Project>
  <PropertyGroup>
    <Company>XperiAndri</Company>
    <Product>Elmish.Uno</Product>
    <Authors>XperiAndri, Dim-37</Authors>
    <Copyright>Copyright © XperiAndri</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <DotNetVersion>net10.0</DotNetVersion>
    <Nullable>enable</Nullable>
    <LangVersion Condition="'$(MSBuildProjectExtension)'=='.csproj'">14.0</LangVersion>
    <LangVersion Condition="'$(MSBuildProjectExtension)'=='.fsproj'">10.0</LangVersion>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <EnableCoreMrtTooling Condition="'$(MSBuildRuntimeType)' == 'Core' AND '$(OutputType)' != 'WinExe' AND '$(OutputType)' != 'Exe'">true</EnableCoreMrtTooling>
  </PropertyGroup>
  <PropertyGroup>
    <WinAppSdkVersion>1.8.251106002</WinAppSdkVersion> <!-- https://www.nuget.org/packages/Microsoft.WindowsAppSDK -->
    <WinAppSdkBuildToolsVersion>10.0.28000.1-RTM</WinAppSdkBuildToolsVersion> <!-- https://www.nuget.org/packages/Microsoft.Windows.SDK.BuildTools -->
    <WindowsSdkPackageVersion>10.0.26100.81</WindowsSdkPackageVersion> <!-- https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref -->
  </PropertyGroup>
</Project>
