name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: [9.0.101]
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install local tools
      run: dotnet tool restore

    - name: Restore NuGet packages
      run: dotnet restore Elmish.Uno.sln

    - name: Build
      run: dotnet build --no-restore Elmish.Uno.sln --configuration Release -maxcpucount

    - name: Test
      run: dotnet test --no-build --configuration Release src/Elmish.Uno.Tests/Elmish.Uno.Tests.fsproj
